name: Build APK

on:
  push:
    branches:
      - main

jobs:
  buildozer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            unzip \
            openjdk-8-jdk \
            libssl-dev \
            libffi-dev \
            python3-dev \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libblas-dev \
            liblapack-dev \
            libatlas-base-dev \
            gfortran \
            cython3 \
            curl

      - name: Install Buildozer
        run: |
          pip install --upgrade cython==0.29.32
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: MyKivyApp-apk
          path: bin/*.apk
